# Basic project configuration
project:
  type: website
  output-dir: ../docs  # Output directory for built site
  resources:
    - "!blog/drafts/"  # Excludes drafts from publication

# Website configuration
website:
  title: "Rømer Chain"
  description: "A First Principles Approach to Blockchain Design"
  site-url: http://romer.network
  repo-url: https://github.com/hariseldon23/Romer
  
  navbar:
    right:  
      - icon: github
        href: https://github.com/Romer-Network/romer
        aria-label: GitHub
      - icon: twitter 
        href: https://x.com/romerchain
        aria-label: Twitter
    left:
      - text: Home
        href: index.qmd
      
      - text: Deck
        href: pitch/index.qmd
      
      - text: Tokenomics
        menu:
          - text: Overview
            href: economics/index.qmd
          - text: Economic Model
            href: economics/model.qmd
          - text: Token Distribution
            href: economics/distribution.qmd
          - text: Market Dynamics
            href: economics/market.qmd
          - text: Validator Economics
            href: economics/validators.qmd
      
      - text: Technical Design
        menu:
          - text: Architecture Overview
            href: technical/index.qmd
          - text: Proof of Physics
            href: technical/pop.qmd
          - text: Network Design
            href: technical/network.qmd
          - text: Development Roadmap
            href: technical/devnet.qmd
          - text: Validator Requirements
            href: technical/validators.qmd
        
      - text: Blog
        href: blog/index.qmd

  sidebar:
    - id: blog
      title: "Blog Navigation"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Recent Posts"
          href: blog/index.qmd
        - text: "Categories"
          href: blog/categories.qmd
        - text: "Archive"
          href: blog/archive.qmd
      search: true

# Blog-specific configuration
blog:
  title: "Rømer Chain Blog"
  description: "Technical insights and development updates from the Rømer Chain team"
  authors:
    - name: "Rømer Chain Team"
      url: https://hariseldon23.github.io/Romer/
  
  # Blog post display settings
  listing:
    contents: "blog/posts"
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    feed: true
    page-size: 10
  
  # Blog post sharing and comments
  sharing: [twitter, linkedin]
  comments:
    giscus:
      repo: hariseldon23/Romer
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: bottom

# Page format configuration
format:
  html:
    # Theme configuration
    theme:
      light: [cosmo]
    
    # Page features
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    code-fold: false
    code-tools: false
    code-link: false
    
    # Typography and layout
    fontsize: 1.0em
    linestretch: 1.7
    
    # Header and footer
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
    
    # CSS customization
    css: styles.css
    
    # General settings
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    citations-hover: true
    footnotes-hover: true