# ==============================================================================
# Rømer Chain Website Configuration
# A comprehensive Quarto configuration for professional documentation
# ==============================================================================

# Project Configuration
# ------------------------------------------------------------------------------
project:
  type: website
  output-dir: ../docs
  # Exclude draft blog posts from publication
  resources:
    - "styles.scss"
    - "!blog/drafts/"
  # Execute Python code in a conda environment
  execute-dir: project
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true

# Website Configuration
# ------------------------------------------------------------------------------
website:
  title: "Rømer Chain"
  description: "A First Principles Approach to Blockchain Design"
  site-url: http://romer.network
  repo-url: https://github.com/Romer-Network/romer
  
  # Open Graph and Twitter Card metadata
  open-graph: true
  twitter-card:
    creator: "@romerchain"
    site: "@romerchain"
    card-style: summary_large_image
  
  # Cookie consent and analytics
  cookie-consent: true
  google-analytics: "G-XXXXXXXXXX"  # Replace with your tracking ID
  
  # Navigation Bar Configuration
  navbar:
    background: white
    search: true
    pinned: true
    collapse: true
    collapse-below: lg
    
    # Left-aligned navigation items
    left:
      - text: "Home"
        href: index.qmd
        icon: house
      
      - text: "Market Makers"
        menu: 
          - text: "Overview"
            href: content/market-makers/index.qmd
            icon: graph-up
          - text: "Partnership Framework"
            href: content/market-makers/partner-framework.qmd
            icon: diagram-3
      
      - text: "Technical Design"
        menu:
          - text: "Architecture Overview"
            href: content/technical/index.qmd
            icon: diagram-2
          - text: "Proof of Physics"
            href: content/technical/pop.qmd
            icon: cpu
          - text: "Network Design"
            href: content/technical/network.qmd
            icon: hdd-network
          - text: "Development Roadmap"
            href: content/technical/roadmap.qmd
            icon: calendar-check
          - text: "FIX Protocol"
            href: content/technical/fix.qmd
            icon: wrench
      
      - text: "Tokenomics"
        menu:
          - text: "Overview"
            href: content/economics/index.qmd
            icon: cash-coin
          - text: "Economic Model"
            href: content/economics/model.qmd
            icon: bank
          - text: "Token Distribution"
            href: content/economics/distribution.qmd
            icon: pie-chart
          - text: "Market Dynamics"
            href: content/economics/market.qmd
            icon: graph-up-arrow
          - text: "Validator Economics"
            href: content/economics/validators.qmd
            icon: shield-check
          - text: "Pitch"
            href: content/pitch/index.qmd
            icon: presentation-chart
      
      - text: "Blog"
        href: content/blog/index.qmd
        icon: newspaper
    
    # Right-aligned navigation items
    right:
      - icon: moon-stars
        href: "#"
        aria-label: "Toggle dark mode"
        id: quarto-dark-toggle1
      - icon: github
        href: https://github.com/Romer-Network/romer
        aria-label: GitHub
      - icon: twitter 
        href: https://x.com/romerchain
        aria-label: Twitter

  # Sidebar Configuration
  sidebar:
    - id: blog
      title: "Blog Navigation"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Recent Posts"
          href: content/blog/index.qmd
        - text: "Categories"
          href: content/blog/categories.qmd
        - text: "Archive"
          href: content/blog/archive.qmd
  
  # Page Footer Configuration
  page-footer:
    left: "Copyright © 2025 Rømer Chain"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/Romer-Network/romer
      - icon: twitter
        href: https://x.com/romerchain

# Blog Configuration
# ------------------------------------------------------------------------------
blog:
  title: "Rømer Chain Blog"
  description: "Technical insights and development updates from the Rømer Chain team"
  authors:
    - name: "Rømer Chain Team"
      url: https://romer.network
      image: team/avatar.jpg
  
  # Blog listing settings
  listing:
    contents: "content/blog/posts"
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    feed: true
    page-size: 10
  
  # Post sharing and comments
  sharing: [twitter, linkedin]
  comments:
    giscus:
      repo: Romer-Network/romer
      repo-id: "R_XXX"  # Replace with your repo ID
      category: Comments
      category-id: "DIC_XXX"  # Replace with your category ID
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: bottom

# Format Configuration
# ------------------------------------------------------------------------------
format:
  html:
    # Theme Configuration
    theme: 
      - cosmo
      - scss/main.scss
    scss:
      sass-options:
        - style: compressed
    dark-mode: true
    
    # Typography
    mainfont: "Inter"
    monofont: "Source Code Pro"
    fontsize: 1.05em
    linestretch: 1.7
  
    
    # Table of Contents
    toc: false
    page-layout: full
    toc-depth: 3
    toc-title: "On this page"
    toc-location: right
    
    # Citations and References
    citation-location: margin
    reference-location: margin
    citations-hover: true
    footnotes-hover: true
    
    # Page Features
    smooth-scroll: true
    anchor-sections: true
    fig-responsive: true
    fig-format: svg
    
    # HTML Features
    html-math-method: katex
    self-contained: false
    
    # Include Custom Headers
    include-in-header:
      - text: |
          <meta name="color-scheme" content="light dark">
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Code+Pro:wght@400;600&display=swap" rel="stylesheet">
    
    # CSS and JavaScript
    js:
      - js/theme-toggle.js
      - js/mathjax-config.js
      - js/analytics.js


# Execution Configuration
# ------------------------------------------------------------------------------
execute:
  freeze: auto
  cache: true
  error: false
  echo: true
  output: true
  warning: false
  enabled: true